[Lab-4] Add detail screens
PeshkovND/effective-web-course pull request #4
Opened 2022-11-19 17:24 UTC by PeshkovND

Пешков Никита

2022-11-24 16:55 UTC, konstantinzelinsky commented
Привет! Проблемы с импортами. Папки называются с маленькой буквы, а в импортах с большой
<img width="942" alt="image" src="https://user-images.githubusercontent.com/57330800/203835498-ea7653e3-d489-4632-989c-62282522dd39.png">

2022-11-24 16:56 UTC, konstantinzelinsky requested changes
Поправить импорты

2022-11-24 17:01 UTC, konstantinzelinsky commented on lab3/.eslintcache
> +[{"D:\\effective-web-course\\lab3\\src\\App.tsx":"1","D:\\effective-web-course\\lab3\\src\\components\\card\\index.tsx":"2","D:\\effective-web-course\\lab3\\src\\components\\footer\\index.tsx":"3","D
Этот файл надо добавить в .gitignore

2022-11-24 17:01 UTC, konstantinzelinsky commented on lab3/src/components/Links/index.tsx
> +          return (
Здесь можно избавиться от return и сократить
`array.map((elem) => <Component />)`

2022-11-24 17:56 UTC, PeshkovND commented
> Поправить импорты
![Снимок](https://user-images.githubusercontent.com/78641960/203844416-6f4dfeea-1f6f-4fa4-afa5-81a503167fbb.PNG)

2022-11-25 09:03 UTC, konstantinzelinsky approved these changes
Принял, 12 баллов

2022-11-25 09:03 UTC, konstantinzelinsky commented on lab3/src/components/Links/index.tsx
> +          <NavLink to={link + elem} key={elem} className={styles.link}>
Лучше использовать шаблонные строки вместо конкатенации строк

2022-11-25 09:03 UTC, merged